//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_drone : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Lt_Trackpad
        {
            get
            {
                return SteamVR_Actions.drone_Lt_Trackpad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Lt_TrackpadPos
        {
            get
            {
                return SteamVR_Actions.drone_Lt_TrackpadPos;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rt_Trackpad
        {
            get
            {
                return SteamVR_Actions.drone_Rt_Trackpad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rt_TrackpadPos
        {
            get
            {
                return SteamVR_Actions.drone_Rt_TrackpadPos;
            }
        }
    }
}
